# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - build-pipeline.yml
    - release-pipeline.yml
variables:
  vmImageName: 'ubuntu-latest'
jobs:
- job: Build
  pool:
    vmImage: $(vmImageName)
  steps:
  - script: |
      echo 'compile application'
    displayName: 'compile'
  - script: |
      echo 'do some unit test'
    displayName: 'unit test'
  - task: ArchiveFiles@2
    displayName: 'Archive files'
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      replaceExistingArchive: true
  - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
    artifact: drop