# Explicitly set none for repositry trigger
trigger:
- none

resources:
  pipelines:
  - pipeline: ci-pipeline # Name of the pipeline resource
    source: CI # Name of the triggering pipeline
    trigger:
      branches:
      - main

variables:
  vmImageName: 'ubuntu-latest'

jobs:
- deployment: Deploy
  displayName: Deploy
  environment: dev
  pool:
    vmImage: $(vmImageName)
  strategy:
    runOnce:
      deploy:
        steps:
        - download: ci-pipeline
          artifact: drop
        - task: ExtractFiles@1
          inputs:
           archiveFilePatterns: '$(PIPELINE.WORKSPACE)/ci-pipeline/drop/$(resources.pipeline.ci-pipeline.runID).zip'
           destinationFolder: '$(agent.builddirectory)'
           cleanDestinationFolder: false
        - script: |
            cat $(agent.builddirectory)/README.md
          displayName: cat